from enum import Enum

class ReasonCode(str, Enum):
    # Validation & Schema
    REJECTED_SCHEMA = "REJECTED_SCHEMA"
    INVALID_ACTION_FORMAT = "INVALID_ACTION_FORMAT"
    PLACEHOLDER_DETECTED = "PLACEHOLDER_DETECTED"
    UNTRUSTED_INSTRUCTION_REJECTED = "UNTRUSTED_INSTRUCTION_REJECTED"
    BLOCKED_LEGACY_PAYLOAD = "BLOCKED_LEGACY_PAYLOAD"
    BLOCKED_MISSING_EVIDENCE = "BLOCKED_MISSING_EVIDENCE"
    BLOCKED_INVALID_PARAMETERS = "BLOCKED_INVALID_PARAMETERS"
    
    # Target & Capability & Policy
    BLOCKED_SAFETY = "BLOCKED_SAFETY"
    BLOCKED_TARGET_UNRESOLVED = "BLOCKED_TARGET_UNRESOLVED"
    BLOCKED_UNKNOWN_CAPABILITY = "BLOCKED_UNKNOWN_CAPABILITY"
    BLOCKED_POLICY_MISSING = "BLOCKED_POLICY_MISSING"
    BLOCKED_POLICY = "BLOCKED_POLICY"
    UNSUPPORTED_ENVIRONMENT_CAPABILITY = "UNSUPPORTED_ENVIRONMENT_CAPABILITY"
    REQUIRES_HUMAN_CAPABILITY = "REQUIRES_HUMAN_CAPABILITY"
    REQUIRES_HUMAN_APPROVAL = "REQUIRES_HUMAN_APPROVAL"
    
    # Confidence
    BLOCKED_LOW_CONFIDENCE = "BLOCKED_LOW_CONFIDENCE"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    
    # Execution & Fault Gates
    ATTESTATION_FAILED = "ATTESTATION_FAILED"
    FAULT_SETUP_FAILED = "FAULT_SETUP_FAILED"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    
    # Postcondition Verification & Rollback
    DIAGNOSED = "DIAGNOSED"
    MUTATION_APPLIED_UNVERIFIED = "MUTATION_APPLIED_UNVERIFIED"
    VERIFIED_RECOVERED = "VERIFIED_RECOVERED"
    VERIFICATION_FAILED_ROLLED_BACK = "VERIFICATION_FAILED_ROLLED_BACK"
    VERIFICATION_FAILED_ROLLBACK_FAILED = "VERIFICATION_FAILED_ROLLBACK_FAILED"
    
    # System
    DUPLICATE_IGNORED = "DUPLICATE_IGNORED"
    CLEANUP_FAILED = "CLEANUP_FAILED"
    BLOCKED_INVALID_QUALIFICATION = "BLOCKED_INVALID_QUALIFICATION"
    ATTESTATION_UNAVAILABLE = "ATTESTATION_UNAVAILABLE"


class TerminalState(str, Enum):
    REJECTED_SCHEMA = "REJECTED_SCHEMA"
    INVALID_ACTION_FORMAT = "INVALID_ACTION_FORMAT"
    BLOCKED_LEGACY_PAYLOAD = "BLOCKED_LEGACY_PAYLOAD"
    BLOCKED_MISSING_EVIDENCE = "BLOCKED_MISSING_EVIDENCE"
    BLOCKED_INVALID_PARAMETERS = "BLOCKED_INVALID_PARAMETERS"
    BLOCKED_SAFETY = "BLOCKED_SAFETY"
    BLOCKED_TARGET_UNRESOLVED = "BLOCKED_TARGET_UNRESOLVED"
    BLOCKED_UNKNOWN_CAPABILITY = "BLOCKED_UNKNOWN_CAPABILITY"
    BLOCKED_POLICY = "BLOCKED_POLICY"
    BLOCKED_LOW_CONFIDENCE = "BLOCKED_LOW_CONFIDENCE"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    ATTESTATION_FAILED = "ATTESTATION_FAILED"
    ATTESTATION_UNAVAILABLE = "ATTESTATION_UNAVAILABLE"
    UNSUPPORTED_ENVIRONMENT_CAPABILITY = "UNSUPPORTED_ENVIRONMENT_CAPABILITY"
    FAULT_SETUP_FAILED = "FAULT_SETUP_FAILED"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"
    DIAGNOSED = "DIAGNOSED"
    MUTATION_APPLIED_UNVERIFIED = "MUTATION_APPLIED_UNVERIFIED"
    VERIFIED_RECOVERED = "VERIFIED_RECOVERED"
    VERIFICATION_FAILED_ROLLED_BACK = "VERIFICATION_FAILED_ROLLED_BACK"
    VERIFICATION_FAILED_ROLLBACK_FAILED = "VERIFICATION_FAILED_ROLLBACK_FAILED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    DUPLICATE_IGNORED = "DUPLICATE_IGNORED"
    CLEANUP_FAILED = "CLEANUP_FAILED"
    BLOCKED_INVALID_QUALIFICATION = "BLOCKED_INVALID_QUALIFICATION"
    REQUIRES_HUMAN_APPROVAL = "REQUIRES_HUMAN_APPROVAL"




